name: weight_planet_calculator
description: Weight planet calculator

version: 1.0.0+1

environment:
  sdk: ">=3.10.0 <4.0.0"

dependencies:
  collection: ^1.19.1
  flutter:
    sdk: flutter
  flutter_hooks: ^0.21.3+1
  google_fonts: ^7.0.2

dev_dependencies:
  build_runner: ^2.10.5
  flutter_gen_runner: ^5.12.0
  flutter_test:
    sdk: flutter
  very_good_analysis: ^10.0.0

flutter_gen:
  output: lib/styles/generated/
  line_length: 80

  integrations:
    image: false

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
